### ISSUE TITLE
Server cannot restore plugin source when instance transfer to other servers

### ISSUE THREAD

**Issue by guotuo1024** [viaflow/server#1]
When container instance transfer to other server, it cannot restore exists plug-ins.

**Comment by sirius1024** [comment]
This issue has been fixed in latest rc version.

**Comment by sirius1024** [comment]
And tips, @guotuo1024 is my another GitHub account for submit issues and make some pull request.

**Comment by guotuo1024** [comment]
I can prove it. :)
